<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>EasyBlackout.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenRGB.NET" Version="3.1.1" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EasyBlackout.Tests" />
  </ItemGroup>
</Project>
